package message;

public enum MessageType {
    AUTH_LOGIN_REQUEST,
    AUTH_TICKET_RESPONSE,
    AUTH_KEY_RESPONSE,
    ACCESS_TICKET_REQUEST,
    ACCESS_REQUEST_VERIFY_REQUEST,
    ACCESS_TICKET_RESPONSE,
    ACCESS_KEY_RESPONSE,
    SERVICE_TICKET_REQUEST,
    SERVICE_REQUEST_VERIFY_REQUEST,
    SERVICE_CONFIRM_RESPONSE;
}
